name = "HDBSCAN"
uuid = "dbf13d8f-d36e-4350-8970-f3a99faba199"
authors = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "0.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
